accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    #サインアップページのビューの呼び出し
    path('signup/',
        views.SignUpView.as_view(),
        name='signup'),

    #サインアップ完了ページのビューの呼び出し
    path('signup_success/',
        views.SignUpSuccessView.as_view(),
        name='signup_success'),
    
    #ログインページの表示
    path('login/',
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'
        ),

    #ログアウトを実行
    path('logout/',
        auth_views.LogoutView.as_view(template_name='logout.html'),
        name='logout'
        ),
]

scoreapp/urls.py
from django.urls import path
from . import views

app_name = 'scoreapp'

urlpatterns = [
    path('',
    views.ScoreListView.as_view(), 
    name='index'),

    path('mypage/',
    views.MypageView.as_view(),
    name='mypage'),

    path('titleform/',
    views.CreateTitleView.as_view(),
    name='titleform'),

    path('scoreform/',
    views.CreateScoreView.as_view(),
    name='scoreform'),

    path('done/',
    views.SuccessView.as_view(),
    name='done'),

    path('contact/',
    views.ContactView.as_view(),
    name='contact'),

    path('studentlist/',
    views.StudentListView.as_view(),
    name='studentlist'),

    path('student/<str:user>',
    views.StudentView.as_view(),
    name='student'),

    path('Japaneselist/',
    views.JapaneseView.as_view(),
    name='Japaneselist'),

    path('Mathlist/',
    views.MathView.as_view(),
    name='Mathlist'),
    
    path('Sciencelist/',
    views.ScienceView.as_view(),
    name='Sciencelist'),

    path('Sociologylist/',
    views.SociologyView.as_view(),
    name='Sociologylist'),

    path('Englishlist/',
    views.EnglishView.as_view(),
    name='Englishlist'),
]

scoreproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scoreapp.urls')),
    path('', include('accounts.urls')),

    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name = "password_reset.html"),
        name ='password_reset'),
    
    path('password_reset/done/',
    auth_views.PasswordResetDoneView.as_view(
        template_name = "password_reset_sent.html"),
    name = 'password_reset_done'),

    path('reset/<uidb64>/<token>',
    auth_views.PasswordResetConfirmView.as_view(
        template_name = "password_reset_form.html"),
    name = 'password_reset_confirm'),

    path('reset/done/',
    auth_views.PasswordResetCompleteView.as_view(
        template_name = "password_reset_done.html"),
    name = 'password_reset_complete'),
]

scoreapp/models.py
from django.db import models
from accounts.models import CustomUser
from django.core import validators

class Testtitle(models.Model):
    title = models.CharField(
        verbose_name='テスト名',
        max_length=50
    ) 
    def __str__(self):
        return self.title

class Student(models.Model):    
    user = models.ForeignKey(
        CustomUser,
        verbose_name='氏名',
        on_delete=models.CASCADE
    )

    testtitle = models.ForeignKey(
        Testtitle,
        verbose_name='テスト名',
        on_delete=models.CASCADE
    )
    
    Japanese = models.IntegerField(
        verbose_name='国語',
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(100),
                    validators.RegexValidator(
                        message='正しい得点を入力してください',
                    )]
    )

    Math = models.IntegerField(
        verbose_name='数学',
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(100),
                    validators.RegexValidator(
                        message='正しい得点を入力してください',
                    )]
    )

    Science = models.IntegerField(
        verbose_name='理科',
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(100),
                    validators.RegexValidator(
                        message='正しい得点を入力してください',
                    )]
    )

    Sociology = models.IntegerField(
        verbose_name='社会',
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(100),
                    validators.RegexValidator(
                        message='正しい得点を入力してください',
                    )]
    )

    English = models.IntegerField(
        verbose_name='英語',
        validators=[validators.MinValueValidator(0),
                    validators.MaxValueValidator(100),
                    validators.RegexValidator(
                        message='正しい得点を入力してください',
                    )]
    )

scoreapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import Testtitle,Student

class TesttitleForm(ModelForm):
    class Meta:
        model = Testtitle
        fields = ['title']

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['testtitle','Japanese', 'Math', 'Science', 'Sociology', 'English']

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'

        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

scoreapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,CreateView,FormView
from django.urls import reverse_lazy
from .forms import TesttitleForm,StudentForm,ContactForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import Student
from django.contrib.auth.models import User
from accounts.models import CustomUser

class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 9

class MypageView(ListView):
    template_name = 'mypage.html'

@method_decorator(login_required, name='dispatch')
class CreateTitleView(CreateView):
    form_class = TesttitleForm
    template_name = 'title_form.html'
    success_url = reverse_lazy('scoreapp:done')

    def form_valid(self, form):
        titledata =form.save(commit=False)
        titledata.save()
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class CreateScoreView(CreateView):
    form_class = StudentForm
    template_name = "score_form.html"
    success_url = reverse_lazy('scoreapp:done')

    def form_valid(self, form):
        scoredata = form.save(commit=False)
        scoredata.user = self.request.user
        scoredata.save()
        return super().form_valid(form)

class SuccessView(TemplateView):
    template_name = 'success.html'

class ScoreListView(ListView):
    template_name = 'index.html'
    queryset = Student.objects.all()

class StudentListView(ListView):
    template_name = 'stu_list.html'
    queryset = CustomUser.objects.all()

class JapaneseView(ListView):
    template_name = 'Japanese.html'
    queryset = Student.objects.order_by('-Japanese')

class MathView(ListView):
    template_name = 'Math.html'
    queryset = Student.objects.order_by('-Math')

class ScienceView(ListView):
    template_name = 'Science.html'
    queryset = Student.objects.order_by('-Science')

class SociologyView(ListView):
    template_name = 'Sociology.html'
    queryset = Student.objects.order_by('-Sociology')

class EnglishView(ListView):
    template_name = 'English.html'
    queryset = Student.objects.order_by('-English')
    

class StudentView(ListView):
    template_name = 'index.html'

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = Student.objects.filter(user=user_id).all()
        return user_list

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('scoreapp:contact')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = \
            '送信者名: {0}\nメールアドレス: {1}\nタイトル:{2}\nメッセージ:\n{3}' \
            .format(name, email, title, message)
        from_email = ''
        to_list = ['t9957652@gmail.com']
        message = EmailMessage(subject=subject,body=message,from_email=from_email,to=to_list,)
        message.send()
        messages.success(
            self.request,'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

scoreapp/templates/English.html
{% extends 'base.html' %}
{% load static %}
{% block title %}科目別-英語{% endblock %}
{% block contents %}
<h6></h6>
<h5>登録済み得点一覧(英語)</h5>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">氏名</th>
          <th scope="col">テスト名</th>
          <th scope="col">点数</th>
        </tr>
      </thead>
      <tbody>
        {% for record in object_list %}
        <tr>
          <td>{{record.user.username}}</td>
          <td>{{record.testtitle}}</td>
          <td>{{record.English}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

scoreapp/templates/Math.html
{% extends 'base.html' %}
{% load static %}
{% block title %}科目別-数学{% endblock %}
{% block contents %}
<h6></h6>
<h5>登録済み得点一覧(数学)</h5>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">氏名</th>
          <th scope="col">テスト名</th>
          <th scope="col">点数</th>
        </tr>
      </thead>
      <tbody>
        {% for record in object_list %}
        <tr>
          <td>{{record.user.username}}</td>
          <td>{{record.testtitle}}</td>
          <td>{{record.Math}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

scoreapp/templates/Science.html
{% extends 'base.html' %}
{% load static %}
{% block title %}科目別-理科{% endblock %}
{% block contents %}
<h6></h6>
<h5>登録済み得点一覧(理科)</h5>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">氏名</th>
          <th scope="col">テスト名</th>
          <th scope="col">点数</th>
        </tr>
      </thead>
      <tbody>
        {% for record in object_list %}
        <tr>
          <td>{{record.user.username}}</td>
          <td>{{record.testtitle}}</td>
          <td>{{record.Science}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

scoreapp/templates/Sociology.html
{% extends 'base.html' %}
{% load static %}
{% block title %}科目別-社会{% endblock %}
{% block contents %}
<h6></h6>
<h5>登録済み得点一覧(社会)</h5>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">氏名</th>
          <th scope="col">テスト名</th>
          <th scope="col">点数</th>
        </tr>
      </thead>
      <tbody>
        {% for record in object_list %}
        <tr>
          <td>{{record.user.username}}</td>
          <td>{{record.testtitle}}</td>
          <td>{{record.Sociology}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

scoreapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  
  <body>

<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{% url 'scoreapp:index' %}">学生管理アプリ</a>
  <ul class="navbar-nav flex-row d-md-none">
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
        <svg class="bi"><use xlink:href="#search"/></svg>
      </button>
    </li>
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <svg class="bi"><use xlink:href="#list"/></svg>
      </button>
    </li>
  </ul>

  <div id="navbarSearch" class="navbar-search w-100 collapse">
    <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
      <div class="offcanvas-lg offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
          <ul class="nav flex-column">
            {% if user.is_authenticated %}
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
              <span>登録</span>
            </h6>              
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'scoreapp:scoreform' %}">
                点数入力
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:titleform' %}">
                テスト名入力
              </a>
            </li>
            {% else %}
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
              <span>登録※ログインして下さい</span>
            </h6>             
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'accounts:signup' %}">
                点数入力
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'accounts:signup' %}">
                テスト名入力
              </a>
            </li>
            {% endif %}
            <hr class="my-3">

            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:studentlist' %}">
                生徒一覧
              </a>
            </li>
          </ul>
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
            <span>科目別得点</span>
          </h6>
          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:Japaneselist' %}">
                国語
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:Mathlist' %}">
                数学
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:Sciencelist' %}">
                理科
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:Sociologylist' %}">
                社会
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:Englishlist' %}">
                英語
              </a>
            </li>
          </ul>

          <hr class="my-3">

          <ul class="nav flex-column mb-auto">
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'scoreapp:contact' %}">
                お問い合わせ
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'accounts:logout' %}">
                ログアウト
              </a>
            {% else %}
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'accounts:signup' %}">
                サインイン
              </a>
            {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      {% block contents %}{% endblock %}
    </main>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js" integrity="sha384-gdQErvCNWvHQZj6XZM0dNsAoY4v+j5P1XDpNkcM3HJG1Yx04ecqIHk7+4VBOCHOG" crossorigin="anonymous"></script>
    <script src="dashboard.js"></script>
  
</body>
</html>

scoreapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}お問い合わせ{% endblock %}

        {% block contents %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <strong>お問い合わせ</strong>
                        {% if messages %}
                        <ul class="list-unstyled" style="list-style: none;">
                            {% for message in messages %}
                            <li {%if message.tags %} class="{{ message.tags }}" {% endif %}>
                                {{ message }}
                            </li>
                            {% endfor %}
                        </ul>
                        {% endif %}

                        <div class="my-5">
                            <form method="post">
                                {% csrf_token %}
                                {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                {% endfor %}
                                <br>
                                <button type="submit"
                                        class="btn btn-primary"
                                        id="sendMessageButton">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <hr>
        </main>
        {% endblock %}

scoreapp/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}学生管理アプリ{% endblock %}

{% block contents %}

{% include "score_list.html" %}

{% endblock %}

scoreapp/templates/mypage.html
<!--P.499-->
{% extends 'base.html' %}

{% block title %}Mypage{% endblock %}

    {% block contents %}

    {% if user.is_authenticated %}
        <br>
        <div style="text-align: center;">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% endif %}
            <a href="{% url 'photo:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}

    <!--投稿一覧テンプレートの組み込み-->
    {% include "photos_list.html" %}
    <!--ページネーションの組み込み-->
    {% include "pagination.html" %}

    {% endblock %}

scoreapp/templates/score_form.html
<!--点数入力-->
{% extends 'base.html' %}
{% block title %}点数入力{% endblock %}

{% block contents %}
<h6><br>自分の得点を入力してください</h6>
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">保存</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

scoreapp/templates/score_list.html
<!--得点表示(全体)-->
<h6></h6>
<h5>登録済み得点一覧</h5>
<div class="table-responsive small">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">氏名</th>
          <th scope="col">テスト名</th>
          <th scope="col">国語</th>
          <th scope="col">数学</th>
          <th scope="col">理科</th>
          <th scope="col">社会</th>
          <th scope="col">英語</th>
        </tr>
      </thead>
      <tbody>
        {% for record in object_list %}
        <tr>
          <td>{{record.user.username}}</td>
          <td>{{record.testtitle}}</td>
          <td>{{record.Japanese}}</td>
          <td>{{record.Math}}</td>
          <td>{{record.Science}}</td>
          <td>{{record.Sociology}}</td>
          <td>{{record.English}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

scoreapp/templates/stu_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}生徒一覧{% endblock %}

{% block contents %}
{% for record in object_list %}
<h6></h6>
<button type="button" class="btn btn-light" onclick=location.href="{% url 'scoreapp:student' user=record.id %}">{{record.username}}</button><br>
{% endfor %}
{% endblock %}

scoreapp/templates/success.html
{% extends 'base.html' %}
{% block title %}入力完了{% endblock %}

    {% block contents %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>入力が完了しました</h4>
            </div>
        </div>
    </div>
    {% endblock %}

scoreapp/templates/title_form.html
<!--テスト名入力-->
{% extends 'base.html' %}
{% block title %}テスト名入力{% endblock %}

{% block contents %}
<h6><br>全体に反映されるので登録の際は注意してください</h6>
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">保存</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}